In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_excel('data/DATA.xlsx',sheet_name='user')

In [3]:
df.isnull().sum()

User                  0
State                 0
ID                    0
Name                  0
HQ                    0
User Designation      0
Mobile                1
Password              0
TA RATE 1           355
TA RATE 2           364
DA RATE             355
NIGHT ALLOWANCE     364
App Used            498
Status              498
dtype: int64

In [4]:
df.columns

Index(['User', 'State', 'ID', 'Name', 'HQ', 'User Designation', 'Mobile',
       'Password', 'TA RATE 1', 'TA RATE 2', 'DA RATE', 'NIGHT ALLOWANCE',
       'App Used', 'Status'],
      dtype='str')

In [5]:
df = df[['State','User Designation','HQ','User','Password']]

In [6]:
df.sort_values(by=['State','User Designation','HQ','User'],inplace=True)

In [7]:
df.head(5)

,State,User Designation,HQ,User,Password
116,Gujarat,ASM,Ahmedabad,Jatin Saini|PGGJ1055,4518
136,Gujarat,ASM,Bhuj,Sahil Mansuri|PGGJ1005,2025
165,Gujarat,ASM,Rajkot,Samir Kotak|PGGJ1121,5545
324,Gujarat,RSM,Ahmedabad,Ravindra Singh Bhadauria|PGGJ1159,8862
115,Gujarat,S.ASM,Surat,Shashi Bhushan Mishra|PGGJ1045,6174

In [8]:
df1 = df[['State','User Designation','HQ','User','Password']]

In [9]:
df1.sample(5)

,State,User Designation,HQ,User,Password
445,Maharashtra,SR,Pune,Anil Gugale|PGMH1289,8426
5,Haryana,SR,Kurukshetra,Saurabh Mourya|PGHR1042,5806
245,Maharashtra,ASM,Thane,Mukesh Somaya|PGMH1200,4455
179,Rajasthan,SR,Bharatpur,Sumit raj|PGRJ1204,2025
281,Madhya Pradesh,SR,Indore,Sourabh Sharma|PGMP1007,3030

In [10]:
df11 = df1.sample(2)

In [11]:
df1.columns

Index(['State', 'User Designation', 'HQ', 'User', 'Password'], dtype='str')

In [12]:
# Create nested dictionary with password at DB level
nested = {}

for _, row in df1.iterrows():
    state = row['State']
    ss = row['User Designation']
    db = row['HQ']
    ws = row['User'] # USER
    pwd = row['Password']

    state_dict = nested.setdefault(state, {})
    ss_dict = state_dict.setdefault(ss, {})
    hq_dict = ss_dict.setdefault(db, {})
    db_dict = hq_dict.setdefault(ws, {"password": pwd, "user": []})

    db_dict["user"].append(ws)

# Save
with open("data/dropdown.json", "w") as f:
    json.dump(nested, f, indent=4)